
### Vocabulary of RCC5 Terms



##### Vocabulary: *OpenBiodiv RCC5 Terms*

```
:RCC5RelationshipTerms a :RCC5Dictionary ;
  skos:prefLabel "OpenBiodiv RCC-5 Vocabulary" .
```

##### Term: *Equals (INT)*

```{r}
:Equals_INT rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Equals (INT)" ;
  rdfs:comment "= EQ(x,y) Equals (intensional)"@en . 
```

##### Term: *Proper Part (INT)*
```{r}
:ProperPart_INT rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Proper Part (INT)" ;
  rdfs:comment "< PP(x,y) Proper Part of (intensional)"@en .
```

##### Term: *Inverse Proper Part (INT)*
```{r}
:InverseProperPart_INT rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Inverse Proper Part (INT)" ;
  rdfs:comment "iPP(x, y) Inverse Proper Part (intensional)"@en .
```


##### Term: *Partially Overlaps (INT)*

```{r}
:PartiallyOverlaps_INT rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Partially Overlaps (INT)" ;
  rdfs:comment "o PO(x,y) Partially Overlaps (intensional)"@en .
```

##### Term: *Disjoint (INT)*

```{r}
:Disjoint_INT rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Disjoint (INT)" ;
  rdfs:comment "! DR(x,y) Disjoint from (intensional)."@en .
```

##### Term: *Equals (OST)*

```{r}
:Equals_OST rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Equals (OST)" ;
  rdfs:comment "= EQ(x,y) Equals (ostensive)"@en . 
```

##### Term: *Proper Part (OST)*
```{r}
:ProperPart_OST rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Proper Part (OST)" ;
  rdfs:comment "< PP(x,y) Proper Part of (ostensive)"@en .
```

##### Term: *Inverse Proper Part (OST)*

```{r}
:InverseProperPart_OST rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Inverse Proper Part (OST)" ;
  rdfs:comment "iPP(x, y) Inverse Proper Part (ostensive)"@en .
```

##### Term: *Partially Overlaps (OST)*

```{r}
:PartiallyOverlaps_OST rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Partially Overlaps (OST)" ;
  rdfs:comment "o PO(x,y) Partially Overlaps (ostensive)"@en .
```

##### Term: *Disjoint (OST)*

```{r}
:Disjoint_OST rdf:type :RCC5Relation ;
  skos:inScheme :RCC5RelationTerms ;
  rdfs:label "Disjoint (OST)" ;
  rdfs:comment "! DR(x,y) Disjoint from (ostensive)."@en .
```

